# Generated by Django 6.0.5 on 2026-05-12 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('ice', 'ICE Candidate')], max_length=10)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='callsession',
            new_name='calls_calls_status_984194_idx',
            old_name='calls_calls_status_idx',
        ),
        migrations.AddField(
            model_name='callsignal',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='calls.callsession'),
        ),
        migrations.AddField(
            model_name='callsignal',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_call_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='callsignal',
            index=models.Index(fields=['call', 'created_at'], name='calls_calls_call_id_ee9ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='callsignal',
            index=models.Index(fields=['sender', 'created_at'], name='calls_calls_sender__8b76de_idx'),
        ),
    ]
